export const LANG_STORAGE_KEY = 'lang'

export const TRANSLATIONS = {
  en: {
    nav: {
      dashboard:   'Dashboard',
      parsingCalc: 'Signal Calculator',
      calculator:  'Calculator',
      journal:     'Journal',
      statistics:  'Statistics',
      settings:    'Settings',
      faq:         'FAQ',
      version:     'v2.0.0 · Offline',
    },
    dashboard: {
      title:        'Dashboard',
      deposit:      'Deposit',
      balance:      'Balance',
      totalPL:      'Total P/L',
      todayPL:      "Today's P/L",
      openTrades:   'Open Trades',
      closedTrades: 'Closed Trades',
      winRate:      'Win Rate',
      avgRR:        'Avg R:R',
      profitFactor: 'Profit Factor',
      expectancy:   'Expectancy',
      avgWin:       'Avg Win',
      avgLoss:      'Avg Loss',
      largestWin:   'Largest Win',
      largestLoss:  'Largest Loss',
      maxDrawdown:  'Max Drawdown',
    },
    calc: {
      titleParsing:  'Signal Calculator',
      titleManual:   'Calculator',
      paste:         'Paste Trading Signal',
      deposit:       'Deposit ($)',
      risk:          'Risk (%)',
      split:         'Split positions',
      split1:        '1 position',
      split2:        '2 positions',
      split4:        '4 positions',
      split8:        '8 positions',
      contractSize:  'Contract Size',
      pipSize:       'Pip Size',
      pipValue:      'Pip Value ($)',
      direction:     'Direction',
      instrument:    'Instrument',
      entry:         'Entry Price',
      stopLoss:      'Stop Loss',
      takeProfits:   'Take Profits',
      addTp:         'Add TP',
      parseBtn:      'Parse & Calculate',
      calcBtn:       'Calculate',
      saveJournal:   'Save to Journal',
      date:          'Date',
      time:          'Time',
      notes:         'Notes',
      saveTrade:     'Save Trade',
      saving:        'Saving…',
      saved:         'Saved!',
      calculating:   'Calculating…',
      placeholderParse:  'Paste a signal and click',
      placeholderManual: 'Fill in the fields and click',
      errDeposit: 'Invalid deposit.',
      errRisk:    'Invalid risk %.',
      errEntry:   'Invalid entry price.',
      errSL:      'Invalid stop loss.',
      errSignal:  'Please paste a trading signal.',
      dirLbl:     'Direction',
      instrLbl:   'Instrument',
      entryLbl:   'Entry',
      slLbl:      'Stop Loss',
      slDist:     'SL Distance',
      riskLot:    'Risk & Lot',
      recLot:     'Recommended Lot',
      riskAmount: 'Risk Amount',
      expLoss:    'Expected Loss',
      tpTargets:  'Take Profit Targets',
      price:      'Price',
      pips:       'Pips',
      profit:     'Profit',
      rr:         'R:R',
      copyLot:    'Copy Lot',
      copyEntry:  'Copy Entry',
      copySL:     'Copy SL',
      noTPsFound: 'No TPs found',
      noTPsSet:   'No TPs set',
      posSplit:   'Position Split',
      posNum:     'Position',
      riskDollar: 'Risk $',
      targetTP:   'Target TP',
      tpPrice:    'TP Price',
      breakEven:    'Break Even after TP1',
      locked:       'Locked profit after TP1',
      remaining:    'Remaining risk after BE',
      warnMinLot:    'Calculated lot ({raw}) is below the broker minimum ({min}).',
      warnMinRiskA:  'To reach minimum lot with ${deposit} deposit: set risk to at least',
      warnMinRiskB:  'To reach minimum lot with {risk}% risk: deposit at least',
      warnSplitMin:  'Minimum lot ({min}) applied to each split position — actual total risk exceeds the intended ${risk}. Lower your split count or increase your deposit.',
    },
    journal: {
      title:         'Trade Journal',
      addTrade:      'Add Trade',
      instrument:    'Instrument',
      direction:     'Direction',
      status:        'Status',
      from:          'From',
      to:            'To',
      all:           'All',
      date:          'Date',
      entry:         'Entry',
      sl:            'SL',
      lot:           'Lot',
      riskPct:       'Risk%',
      profit:        'Profit',
      actions:       'Actions',
      noTrades:      'No trades found.',
      showing:       'Showing',
      of:            'of',
      trades:        'trades',
      deleteConfirm: 'Delete this trade? This cannot be undone.',
      saveFailed:    'Save failed: ',
    },
    statistics: {
      title:       'Statistics',
      equity:      'Equity Curve',
      balance:     'Balance Curve',
      monthly:     'Monthly Profit',
      winLoss:     'Win / Loss',
      drawdown:    'Drawdown',
      rrDist:      'RR Distribution',
      profitDist:  'Profit Distribution',
    },
    settings: {
      title:       'Settings',
      currency:    'Currency',
      deposit:     'Default Deposit',
      risk:        'Default Risk (%)',
      minLot:      'Minimum Lot Size',
      minLotHint:    'Broker minimum lot (FxPro default: 0.01). Split positions are clamped to this value.',
      defaultSplit:  'Default Split Positions',
      save:          'Save Settings',
      saving:      'Saving…',
      saved:       'Settings saved!',
      failed:      'Failed to save: ',
    },
    modal: {
      addTrade:  'Add Trade',
      editTrade: 'Edit Trade',
      date:      'Date',
      time:      'Time',
      instr:     'Instrument',
      direction: 'Direction',
      status:    'Status',
      entry:     'Entry',
      sl:        'Stop Loss',
      lot:       'Lot',
      riskPct:   'Risk %',
      tps:       'Take Profits (comma-separated)',
      pl:        'Profit / Loss ($)',
      notes:     'Notes',
      cancel:    'Cancel',
      save:      'Save',
    },
    faq: {
      title:          'FAQ',
      core:           'Core Concepts',
      parsingSection: 'How to use: Parsing Calculator',
      manualSection:  'How to use: Calculator (Manual)',
      resultsSection: 'Understanding the Results',
    },
  },

  uk: {
    nav: {
      dashboard:   'Огляд',
      parsingCalc: 'Калькулятор сигналів',
      calculator:  'Калькулятор',
      journal:     'Журнал',
      statistics:  'Статистика',
      settings:    'Налаштування',
      faq:         'Питання та відповіді',
      version:     'v2.0.0 · Офлайн',
    },
    dashboard: {
      title:        'Огляд',
      deposit:      'Депозит',
      balance:      'Баланс',
      totalPL:      'Загальний P/L',
      todayPL:      'P/L сьогодні',
      openTrades:   'Відкриті угоди',
      closedTrades: 'Закриті угоди',
      winRate:      'Прибуткових угод',
      avgRR:        'Сер. R:R',
      profitFactor: 'Фактор прибутку',
      expectancy:   'Математ. очікування',
      avgWin:       'Сер. прибуток',
      avgLoss:      'Сер. збиток',
      largestWin:   'Найбільший прибуток',
      largestLoss:  'Найбільший збиток',
      maxDrawdown:  'Макс. просідання',
    },
    calc: {
      titleParsing:  'Калькулятор сигналів',
      titleManual:   'Калькулятор',
      paste:         'Вставте торговий сигнал',
      deposit:       'Депозит ($)',
      risk:          'Ризик (%)',
      split:         'Поділ позицій',
      split1:        '1 позиція',
      split2:        '2 позиції',
      split4:        '4 позиції',
      split8:        '8 позицій',
      contractSize:  'Розмір контракту',
      pipSize:       'Розмір піпа',
      pipValue:      'Вартість піпа ($)',
      direction:     'Напрямок',
      instrument:    'Інструмент',
      entry:         'Ціна входу',
      stopLoss:      'Стоп-лосс',
      takeProfits:   'Тейк-профіти',
      addTp:         'Додати TP',
      parseBtn:      'Розпарсити та обчислити',
      calcBtn:       'Обчислити',
      saveJournal:   'Зберегти до журналу',
      date:          'Дата',
      time:          'Час',
      notes:         'Нотатки',
      saveTrade:     'Зберегти угоду',
      saving:        'Збереження…',
      saved:         'Збережено!',
      calculating:   'Обчислення…',
      placeholderParse:  'Вставте сигнал та натисніть',
      placeholderManual: 'Заповніть поля та натисніть',
      errDeposit: 'Невірний депозит.',
      errRisk:    'Невірний ризик %.',
      errEntry:   'Невірна ціна входу.',
      errSL:      'Невірний стоп-лосс.',
      errSignal:  'Будь ласка, вставте торговий сигнал.',
      dirLbl:     'Напрямок',
      instrLbl:   'Інструмент',
      entryLbl:   'Вхід',
      slLbl:      'Стоп-лосс',
      slDist:     'Відстань SL',
      riskLot:    'Ризик та лот',
      recLot:     'Рекомендований лот',
      riskAmount: 'Сума ризику',
      expLoss:    'Очікуваний збиток',
      tpTargets:  'Цілі тейк-профіту',
      price:      'Ціна',
      pips:       'Піпи',
      profit:     'Прибуток',
      rr:         'R:R',
      copyLot:    'Копіювати лот',
      copyEntry:  'Копіювати вхід',
      copySL:     'Копіювати SL',
      noTPsFound: 'TP не знайдено',
      noTPsSet:   'TP не задано',
      posSplit:   'Поділ позицій',
      posNum:     'Позиція',
      riskDollar: 'Ризик $',
      targetTP:   'Цільовий TP',
      tpPrice:    'Ціна TP',
      breakEven:    'Беззбитковість після TP1',
      locked:       'Зафіксований прибуток після TP1',
      remaining:    'Залишковий ризик після BE',
      warnMinLot:    'Розрахований лот ({raw}) є меншим за мінімум брокера ({min}).',
      warnMinRiskA:  'Щоб досягти мін. лота при депозиті ${deposit}: встановіть ризик не менше',
      warnMinRiskB:  'Щоб досягти мін. лота при ризику {risk}%: поповніть депозит до',
      warnSplitMin:  'Мінімальний лот ({min}) застосовано до кожної позиції — фактичний сукупний ризик перевищує заплановані ${risk}. Зменшіть кількість позицій або збільшіть депозит.',
    },
    journal: {
      title:         'Журнал угод',
      addTrade:      'Додати угоду',
      instrument:    'Інструмент',
      direction:     'Напрямок',
      status:        'Статус',
      from:          'Від',
      to:            'До',
      all:           'Всі',
      date:          'Дата',
      entry:         'Вхід',
      sl:            'SL',
      lot:           'Лот',
      riskPct:       'Ризик%',
      profit:        'Прибуток',
      actions:       'Дії',
      noTrades:      'Угоди не знайдено.',
      showing:       'Показано',
      of:            'з',
      trades:        'угод',
      deleteConfirm: 'Видалити цю угоду? Це незворотньо.',
      saveFailed:    'Помилка збереження: ',
    },
    statistics: {
      title:       'Статистика',
      equity:      'Крива капіталу',
      balance:     'Крива балансу',
      monthly:     'Щомісячний прибуток',
      winLoss:     'Прибуткові / Збиткові',
      drawdown:    'Просідання',
      rrDist:      'Розподіл R:R',
      profitDist:  'Розподіл прибутку',
    },
    settings: {
      title:       'Налаштування',
      currency:    'Валюта',
      deposit:     'Депозит за замовч.',
      risk:        'Ризик за замовч. (%)',
      minLot:      'Мінімальний розмір лота',
      minLotHint:    'Мінімальний лот брокера (FxPro: 0.01). Позиції при поділі обмежуються цим значенням.',
      defaultSplit:  'Кількість позицій за замовчуванням',
      save:          'Зберегти налаштування',
      saving:      'Збереження…',
      saved:       'Налаштування збережено!',
      failed:      'Помилка збереження: ',
    },
    modal: {
      addTrade:  'Додати угоду',
      editTrade: 'Редагувати угоду',
      date:      'Дата',
      time:      'Час',
      instr:     'Інструмент',
      direction: 'Напрямок',
      status:    'Статус',
      entry:     'Вхід',
      sl:        'Стоп-лосс',
      lot:       'Лот',
      riskPct:   'Ризик %',
      tps:       'Тейк-профіти (через кому)',
      pl:        'Прибуток / Збиток ($)',
      notes:     'Нотатки',
      cancel:    'Скасувати',
      save:      'Зберегти',
    },
    faq: {
      title:          'Питання та відповіді',
      core:           'Основні поняття',
      parsingSection: 'Як користуватися: Калькулятор сигналів',
      manualSection:  'Як користуватися: Калькулятор (вручну)',
      resultsSection: 'Розуміння результатів',
    },
  },
}
